[project]
name = "lekit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lerobot>=0.5.1",
    "pyzmq>=27.1.0",
    "textual>=8.2.8",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true

[tool.ruff]
line-length = 120
target-version = "py313"
exclude = ["tests/artifacts/**/*.safetensors"]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
