"""Control Hub domain models and wire codecs."""

from .cli import build_parser, derive_advertise_endpoint
from .codec import decode_action_envelope, decode_management, encode_action_envelope, encode_management
from .controller import ControllerNode, ControllerNodeConfig, HandleExpired, HandleNotGranted
from .discovery import (
    DEFAULT_DISCOVERY_PORT,
    DEFAULT_MULTICAST_GROUP,
    CooperativeDiscoveryListener,
    DiscoveryBeacon,
    HubBeaconListener,
    HubBeaconPublisher,
)
from .handles import (
    HandleRecord,
    HandleTransition,
    InvalidHandleTransition,
    StaleTransition,
    correlate_control,
    transition_handle,
)
from .hub import (
    ControlConflict,
    ControlError,
    Hub,
    HubConfig,
    IncompatibleNode,
    NodeUnavailable,
)
from .memory_runtime import MemoryRuntime
from .model import (
    PROTOCOL_VERSION,
    TERMINAL_HANDLE_STATES,
    ActionEnvelope,
    ControlHandle,
    ControllerControlState,
    ControlSnapshot,
    HandleState,
    HubSnapshot,
    ManagementMessage,
    NodeDescriptor,
    NodeReport,
    NodeRole,
    NodeSnapshot,
    RobotControlState,
    RuntimeState,
    TimingConfig,
    load_or_create_node_id,
    normalize_feature_metadata,
)
from .robot import HoldResult, PassiveHold, PayloadProcessor, RobotNode, RobotNodeConfig
from .runtime import (
    ActionPublisher,
    HubChannel,
    LatestActionReceiver,
    NodeChannel,
    ReceivedAction,
    ReceivedManagement,
    Runtime,
)
from .web import create_hub_app
from .zmq_runtime import (
    MalformedAction,
    ZmqActionPublisher,
    ZmqContextOwner,
    ZmqHubChannel,
    ZmqLatestActionReceiver,
    ZmqNodeChannel,
    ZmqRuntime,
)

__all__ = [
    "PROTOCOL_VERSION",
    "TERMINAL_HANDLE_STATES",
    "ActionEnvelope",
    "ActionPublisher",
    "ControlHandle",
    "ControlConflict",
    "ControlError",
    "ControllerNode",
    "ControllerNodeConfig",
    "ControllerControlState",
    "ControlSnapshot",
    "CooperativeDiscoveryListener",
    "DEFAULT_DISCOVERY_PORT",
    "DEFAULT_MULTICAST_GROUP",
    "DiscoveryBeacon",
    "HandleState",
    "HandleRecord",
    "HandleTransition",
    "HubSnapshot",
    "HubChannel",
    "Hub",
    "HubConfig",
    "HubBeaconListener",
    "HubBeaconPublisher",
    "HubStore",
    "HandleExpired",
    "HandleNotGranted",
    "IncompatibleNode",
    "InvalidHandleTransition",
    "ManagementMessage",
    "MalformedAction",
    "MemoryRuntime",
    "LatestActionReceiver",
    "HoldResult",
    "NodeChannel",
    "NodeDescriptor",
    "NodeReport",
    "NodeRole",
    "NodeSnapshot",
    "NodeUnavailable",
    "PassiveHold",
    "PayloadProcessor",
    "RobotControlState",
    "RobotNode",
    "RobotNodeConfig",
    "ReceivedAction",
    "ReceivedManagement",
    "Runtime",
    "RuntimeState",
    "StaleTransition",
    "TimingConfig",
    "decode_action_envelope",
    "decode_management",
    "derive_advertise_endpoint",
    "encode_action_envelope",
    "encode_management",
    "correlate_control",
    "load_or_create_node_id",
    "normalize_feature_metadata",
    "transition_handle",
    "ZmqActionPublisher",
    "ZmqContextOwner",
    "ZmqHubChannel",
    "ZmqLatestActionReceiver",
    "ZmqNodeChannel",
    "ZmqRuntime",
    "create_hub_app",
    "build_parser",
]

from .store import HubStore
