# rerun: rerun+http://localhost:9876/proxy

robot:
  type: ros_robot
  enable: bimanual
  cameras:
    head: { type: opencv, camera_index: 4, fps: 60, width: 640, height: 480, fourcc: MJPG }
    left: { type: opencv, camera_index: 2, fps: 60, width: 640, height: 480, fourcc: MJPG }
    right: { type: opencv, camera_index: 0, fps: 60, width: 640, height: 480, fourcc: MJPG }

tasks:
  - id: 1
    prompt: pick up the yellow bin from the table with the left arm
    policy: tcp://172.20.69.32:9005
    budget: 60.0  # time budget in seconds
    preset:
      location: C
      torso_height: 0.55
      joint_angles:
        - [0.3, 0.0, 0.0, 2.1, 0.0, 0.27, 0.0, 0.0, -0.3, 0.0, 0.0, -2.1, 0.0, -0.27, 0.0, 0.0]
      # You can set multiple steps to move robot arms sequentially in preset progress.

  - id: 2
    prompt: handover the yellow bin from the left arm to the right arm
    policy: tcp://172.20.69.32:9005
    budget: 30.0
    preset:
      location: E
      torso_height: 0.55
      joint_angles:
        - [-0.35, 0.0, 0.0, 1.97, 0.0, 0.7, 0.0, 1.0, -0.3, 0.0, 0.0, -2.1, 0.0, -0.27, 0.0, 0.0]
        - [-0.703, -0.892, 0.905, 1.119, -1.276, -0.263, 0.9, 1.0, -0.3, 0.842, 0.0, -1.8, 0.9, -0.17, -0.2, 0.0]
        - [-0.703, -0.892, 0.905, 1.119, -1.276, -0.263, 1.534, 1.0, 0.792, 0.842, -0.881, -1.674,1.104,-0.061, -0.4, 0.0]

  - id: 3
    prompt: place the yellow bin into the left-side rail
    policy: tcp://172.20.69.32:9005
    budget: 30.0
    preset:
      location: A
      torso_height: 0.65
      joint_angles:
        - [-0.7, -0.9, 0.5, 1.1, -1.3, -0.1, 0.5, 0.0, 0.792, 0.842, -0.881, -1.674,1.104,-0.061, -0.4, 1.0]
        - [-0.2, -0.6, 0.2, 1.6, -0.8, -0.1, 0.3, 0.0, -0.3, 0.6, 0.0, -1.9, 0.9, -0.27, 0.0, 1.0]
        - [0.3, 0.0, 0.0, 2.1, 0.0, 0.27, 0.0, 0.0, -0.3, 0.0, 0.0, -2.1, 0.0, -0.27, 0.0, 1.0]


  - id: 4
    prompt: place the yellow bin into the right-side rail
    policy: tcp://172.20.69.32:9005
    budget: 30.0
    preset:
      location: A
      torso_height: 0.65
      joint_angles:
        - [0.3, 0.0, 0.0, 2.1, 0.0, 0.27, 0.0, 0.0, -0.3, 0.0, 0.0, -2.1, 0.0, -0.27, 0.0, 1.0]

  - id: 5
    prompt: pick the yellow bin from the rack with the right arm
    policy: tcp://172.20.69.32:9005
    budget: 30.0
    preset:
      location: B
      torso_height: 0.53
      joint_angles:
        - [0.3, 0.0, 0.0, 2.1, 0.0, 0.27, 0.0, 0.0, -0.3, 0.0, 0.0, -2.1, 0.0, -0.27, 0.0, 0.0]

  - id: 6
    prompt: place the bin on the table
    policy: rule-based
    budget: 10.0
    preset:
      location: D
      torso_height: 0.53
      joint_angles:
        - [0.68, 0.0, 0.0, 2.29, 0.0, 0.02, 0.0, 0.0, -0.68, 0.0, 0.0, -2.29, 0.0, -0.02, 0.0, 1.0]
